title: Xin (Crystal) Sun
logo: /assets/img/me.png
email: crystal9401@gmail.com
description: Climbing a mountain called data science :)
google_analytics:
theme: jekyll-theme-minimal

# SNS setting
github_username: crystalxs
